// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for SubsetFunction
 */
export interface SubsetFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/personen/subset/subset.
 */
export class SubsetFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: SubsetFunctionProps) {
    super(scope, id, {
      description: 'src/personen/subset/subset.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/personen/subset/subset.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}