// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for PartnerFilterFunction
 */
export interface PartnerFilterFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/personen/partner-filter/partner-filter.
 */
export class PartnerFilterFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: PartnerFilterFunctionProps) {
    super(scope, id, {
      description: 'src/personen/partner-filter/partner-filter.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/personen/partner-filter/partner-filter.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}